In [1]:
# importing packages
import numpy as np
import scipy as sp
from sklearn.cluster import spectral_clustering
from sklearn.feature_extraction import image
import cv2
import matplotlib.pyplot as plt
from skimage.transform import resize
import os
from os.path import join
import networkx as nx
import scipy.sparse

In [2]:
N_REGIONS = 25
beta = 5
eps = 1e-6
p = 0.1

In [3]:
dir = r'C:\Users\mvijitha22\jupyter_codes\Rafaela\GraphEncoder\GraphEncoder'
os.chdir(dir)

In [4]:
cam = os.path.join(dir, './data/')
latest_subdir = max([os.path.join(cam,d) for d in os.listdir(cam)], key=os.path.getmtime)
print(str(latest_subdir))
folder = latest_subdir
count = 0
steps = 0
maxPixel= 12
imageSize = maxPixel * maxPixel
num_features = imageSize

cam_graph = os.path.join(dir, './graph/')
print(str(cam_graph))
all_folders = os.listdir(cam_graph)
os.chdir(cam_graph)
retval = os.getcwd()
all_folders.sort()
latest = all_folders[-1].replace('S', '')
new = int(latest) + 1
mydir = 'S'+str(new)
print(str(mydir))
os.makedirs(mydir)

# Iterate directory
for path in os.listdir(folder):
    # check if current path is a file
    if os.path.isfile(os.path.join(folder, path)):
        count += 1
print('File count:', count)

C:\Users\mvijitha22\jupyter_codes\Rafaela\GraphEncoder\GraphEncoder\./data/S6
C:\Users\mvijitha22\jupyter_codes\Rafaela\GraphEncoder\GraphEncoder\./graph/
S9
File count: 42


In [5]:
F = nx.Graph()

In [6]:
for f in range(count):
    print(str(steps))
    print(str(f))
    # reading image
    data = 'Frame' + str(steps) + '.png'
    path = join(folder, data)
    print(path)
    def read_image():
        img = cv2.imread(path, 0)
        return img

    cartpole = read_image()
    print ("img_processing.size=",cartpole.size)
    imageSize=maxPixel*maxPixel
    cartpole = resize(cartpole, (maxPixel, maxPixel))
    print ("img_processing.size=",cartpole.size)
    # Downsample the image by a factor of 4
    print(cartpole.shape)
    mask = cartpole.astype(bool)
    cartpole = cartpole.astype(float)
    print(cartpole.shape)

    # Convert the image into a graph with the value of the gradient on the
    # edges.
    import random

    if True:
        graph = image.img_to_graph(cartpole, mask=mask, return_as=np.ndarray)
        arr = image.img_to_graph(cartpole, mask=mask, return_as=np.ndarray)
        graph1 = image.img_to_graph(cartpole)

        G = nx.from_numpy_array(arr)
        G.edges(data=True)

        row = []
        col = []
        data = []

        for i in range(graph.shape[0]):
            for j in range(graph.shape[1]):
                if graph[i][j] != 0:
                    row.append(i)
                    col.append(j)
                    data.append(graph[i][j])

        graph = sp.sparse.coo_matrix((data, (row,col)), shape=graph.shape, dtype = float)
    else:
        graph = image.img_to_graph(cartpole)

    # Take a decreasing function of the gradient: an exponential
    # The smaller beta is, the more independent the segmentation is of the
    # actual image. For beta=1, the segmentation is close to a voronoi
    graph.data = np.exp(-beta * graph.data / cartpole.std()) + eps
    #concat graph F
    F = nx.compose(F,G)
    steps += 1   
f += 1

0
0
C:\Users\mvijitha22\jupyter_codes\Rafaela\GraphEncoder\GraphEncoder\./data/S6\Frame0.png
img_processing.size= 240000
img_processing.size= 144
(12, 12)
(12, 12)
1
1
C:\Users\mvijitha22\jupyter_codes\Rafaela\GraphEncoder\GraphEncoder\./data/S6\Frame1.png
img_processing.size= 240000
img_processing.size= 144
(12, 12)
(12, 12)
2
2
C:\Users\mvijitha22\jupyter_codes\Rafaela\GraphEncoder\GraphEncoder\./data/S6\Frame2.png
img_processing.size= 240000
img_processing.size= 144
(12, 12)
(12, 12)
3
3
C:\Users\mvijitha22\jupyter_codes\Rafaela\GraphEncoder\GraphEncoder\./data/S6\Frame3.png
img_processing.size= 240000
img_processing.size= 144
(12, 12)
(12, 12)
4
4
C:\Users\mvijitha22\jupyter_codes\Rafaela\GraphEncoder\GraphEncoder\./data/S6\Frame4.png
img_processing.size= 240000
img_processing.size= 144
(12, 12)
(12, 12)
5
5
C:\Users\mvijitha22\jupyter_codes\Rafaela\GraphEncoder\GraphEncoder\./data/S6\Frame5.png
img_processing.size= 240000
img_processing.size= 144
(12, 12)
(12, 12)
6
6
C:\Users\mvi

In [7]:
F

In [23]:
from torch_geometric.utils.convert import from_networkx, to_networkx
from torch_geometric.data import Data as gData
import torch
import scipy as sp
from torch_geometric.data import Data
from scipy import sparse

In [9]:
required_graph = from_networkx(F)

In [10]:
print(required_graph)
print(required_graph.x)
print(required_graph.y)

Data(edge_index=[2, 336], weight=[336], num_nodes=144)
None
None


In [20]:
required_graph.num_node_features

0

In [ ]:
#Edge index

In [11]:
required_graph.edge_index

tensor([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
          14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
          28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,
          41,  42,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  52,
          52,  53,  53,  53,  53,  53,  54,  54,  54,  54,  54,  55,  55,  56,
          57,  58,  59,  60,  61,  62,  63,  63,  64,  64,  64,  64,  64,  65,
          65,  65,  65,  65,  66,  66,  66,  66,  66,  67,  67,  68,  69,  70,
          71,  72,  72,  73,  73,  74,  74,  75,  75,  75,  76,  76,  76,  76,
          76,  77,  77,  77,  77,  77,  78,  78,  78,  78,  78,  79,  79,  79,
          80,  80,  81,  81,  82,  82,  83,  83,  84,  84,  84,  85,  85,  85,
          86,  86,  86,  87,  87,  87,  87,  88,  88,  88,  88,  88,  89,  89,
          89,  89,  89,  90,  90,  90,  90,  90,  91,  91,  91,  91,  92,  92,
          92,  93,  93,  93,  94,  94,  94,  95,  95

In [ ]:
#x value

In [12]:
adj_matrix = nx.adjacency_matrix(F)
adj_matrix

<144x144 sparse matrix of type '<class 'numpy.float64'>'
	with 336 stored elements in Compressed Sparse Row format>

In [13]:
adj_array = nx.to_numpy_array(F) #get adjacence matrix as numpy array
adj_array

array([[0.99607843, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.99607843, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.99607843, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.99607843, 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.99607843,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.99607843]])

In [17]:
adj_array_second = nx.to_numpy_array(required_graph) #get adjacence matrix as numpy array
adj_array_second

AttributeError: 'GlobalStorage' object has no attribute 'is_multigraph'

In [14]:
adj_array.shape

(144, 144)

In [18]:
edge_list = list(F.edges())
edge_index = torch.tensor(edge_list, dtype=torch.long)

In [29]:
sparse_array = sparse.csr_matrix(adj_matrix).toarray() 
coo_array = sparse.coo_matrix(adj_matrix)
#ArrayG_coo = nx.to_scipy_sparse_array(F, format='coo')
print(sparse_array.shape)

(144, 144)


In [30]:
values = coo_array.data
indices = np.vstack((coo_array.row, coo_array.col))

datasetG_index = torch.LongTensor(indices)
v = torch.FloatTensor(values)
shape = sparse_array.shape

required_graph.x = torch.sparse.FloatTensor(datasetG_index, v, torch.Size(shape)).to_dense()

In [31]:
numpy_arr = np.array([F.nodes],dtype="float64")
required_graph.y = torch.from_numpy(numpy_arr)

In [36]:
# Split the data
train_ratio = 0.2
num_nodes = required_graph.x.shape[0]
num_train = int(num_nodes * train_ratio)
idx = [i for i in range(num_nodes)]

np.random.shuffle(idx)
train_mask = torch.full_like(required_graph.y, False, dtype=bool)
#train_mask[idx[:num_train]] = True
test_mask = torch.full_like(required_graph.y, False, dtype=bool)
#test_mask[idx[num_train:]] = True
val_mask = test_mask

print(train_mask)
print(test_mask)
print(val_mask)

tensor([[False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, F

In [38]:
required_graph.x.shape[0]

144

In [51]:
from torch_geometric.nn import VGAE
from torch_geometric.utils import train_test_split_edges
import torch_geometric.transforms as T
from torch_geometric.nn import GCNConv
from torch_geometric.data import Data

In [52]:


num_nodes = 144
num_node_features = required_graph.x.shape[0]
num_edge_features = 1

x = torch.tensor([num_nodes,num_node_features], dtype=torch.float)

data = Data(x=required_graph.x, edge_index=edge_index.t().contiguous())

In [53]:

class VariationalGCNEncoder(torch.nn.Module):
    def __init__(self, in_channels, out_channels):
        super(VariationalGCNEncoder, self).__init__()
        self.conv1 = GCNConv(in_channels, 2 * out_channels, cached=True) # cached only for transductive learning
        self.conv_mu = GCNConv(2 * out_channels, out_channels, cached=True)
        self.conv_logstd = GCNConv(2 * out_channels, out_channels, cached=True)

    def forward(self, x, edge_index):
        x = self.conv1(x, edge_index).relu()
        return self.conv_mu(x, edge_index), self.conv_logstd(x, edge_index)

In [54]:
out_channels = 2
num_features = required_graph.x.shape[0]
epochs = 10


model = VGAE(VariationalGCNEncoder(num_features, out_channels))  # new line

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model = model.to(device)
x = data.x.to(device)
train_pos_edge_index = data.train_pos_edge_index.to(device)
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)

AttributeError: 'GlobalStorage' object has no attribute 'train_pos_edge_index'